---
title: "Gráficos"
author: "Francisco Alberto"
date: "30/9/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Gráficos

```{r,mi_primer_plot,fig.cap="Primer Gráfico"}
x = seq(1,5,1)
y = seq(4,8,1)
plot(x,y,type = "l", col = "purple", lwd = 2 ,
     lty = "dotdash")
legend("bottomright",
       legend = c("x","y"))


```
```{r,fig.cap="Segundo Gráfico"}
plot(2^(1:6))
```

```{r,fig.cap="Tercer Gráfico"}
cuadrado = function(x){x^2}
plot(cuadrado, col = "green",lwd = 2 , 
     main = "Función cuadrado", xlim = c(-3,3),
     ylab = expression(f(x)))
legend("bottomleft",
       legend = c(expression(x^2)),col = "green",
       lwd = 2)


```

```{r,fig.cap="Cuarto Gráfico"}
x = c(14,16,18,19)
raiz_cuadrada = function(x){sqrt(x)}
plot(raiz_cuadrada, main = "Raiz cuadrada",
     xlab = "x", ylab = expression(f(x)),
     type = "l", lty = "dotdash",lwd = 2,
     col = "orange")
legend("bottomright",
      legend = c(expression(sqrt(x))),lwd = 2,
      lty = "dotdash", col = "orange")
```

## Parámetros

```{r,fig.align='center'}
par(mfrow = c(1,2))
x = 1:20
triple = function(x){x ^ 3}
plot(triple(x),xlab = "Indices",
     ylab = "Exponentes",main = "Triple",
     pch = 20 , cex = 2,col = "red")
legend("topleft",
       legend = c(expression(x^3)),col = "red",
       pch = 20)
plot(triple(x),xlab = "Indices",
     ylab = "Exponentes",main = "Triple",
     pch = 20 , cex = 2,col = "blue")
legend("topleft",
       legend = c(expression(x^3)),col = "blue",
       pch = 20)
par(mfrow = c(1,1))
```

```{r}
x = 1:20
logaritmico = function(x){log10(x)}
plot(logaritmico(x),xlab = "indices",
     ylab = expression(f(x)),log = "y",
     main = "Gráfico logarítmico",pch = 20,
     col = "blue",cex = 3,type = "b")
legend("bottomright",
       legend = c(expression(log10(x))),
       col = "blue",pch = 20)

```

```{r}
x = c(1,2,3,4,5,6)
y = c(2,3,7,8,9,10)
plot(x,y,main = "Gráfico 1",pch = 23,col = "blue",
     bg = "red",lty = "dotdash",type = "b",
     lwd = 2,xaxp = c(0,6,3),yaxp = c(0,10,5))


```

```{r}
c = function(x){x^3}
plot(c,xlab = "x",ylab = expression(f(x)),
     main = "Grafico cubo",
     pch = 19 , lty = "dotdash",lwd = 2,
     col = "red", xlim = c(-9,9))
abline(v = -2:2 , h = 0:6, lty = "dashed",
       col = "gray0")
```




